/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\scene.gltf --transform 
Files: .\scene.gltf [12.45KB] > C:\Users\LENOVO\Downloads\computer_terminal\scene-transformed.glb [533.64KB] (-4186%)
Author: Chris Sweetwood (https://sketchfab.com/ChrisSweetwood)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/computer-terminal-b3a26b00c5b04eedad0a1cdca884130f
Title: Computer Terminal
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Comp_Screen000_TerminalMaterial_0.geometry} material={materials.TerminalMaterial} position={[0, -0.2, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.47} />
    </group>
  )
}
useGLTF.preload('/Model.glb')